language: elixir

notifications:
  email: false

sudo: required

elixir:
  - 1.7.2

otp_release:
  - 21.0

env:
  DOCKER_COMPOSE_VERSION: 1.8.0

sudo: required

services:
  - docker

before_script:
  - ./start-test-broker.sh

script:
  - mix test

